# Generated by Django 3.0.3 on 2020-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200514_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
